### PR TITLE
add Chihiro, the worst bot in existence

### PR DESCRIPTION
**Pull request by snarkyllama**

### CODE REVIEW

**Comment by AlexFlipnote** [comment]
The image is too huge, please reduce it to something smaller than 100KB

**Comment by AlexFlipnote** [comment]
Actually, use the default URL to Discord PNG format

**Comment by snarkyllama** [comment]
Ok, the avatar URL issue **should** be fixed.

**Comment by snarkyllama** [comment]
Ok, _should_ be fixed.

**Pull request merged**
