### PR TITLE
Add better bot

### PR DESCRIPTION
**Pull request by perryprog**
btw this a clone of https://git.terminal.ink/perryprog/BestBotList and http://bots.pprogs.blog

### CODE REVIEW

**Comment by Devoxin** [comment]
trash

**Comment by Saederup92** [comment]
hash

**Comment by perryprog** [comment]
clone

**Comment by Saederup92** [comment]
@perryprog No u

**Comment by perryprog** [comment]
wait can I dcma my own repo

**Comment by Devoxin** [comment]
delet this

**Comment by perryprog** [comment]
how do I report my repo ahhhhh

**Comment by perryprog** [comment]
CLICC CLICC

**Comment by Saederup92** [comment]
Cluck cluck cluck

**Comment by perryprog** [comment]
rip

we'll rip that meme

**Comment by Saederup92** [comment]
image

**Comment by Devoxin** [comment]
*waits for Alex to swoop in with `jeez, the notifications...`*

**Comment by perryprog** [comment]
I miss my meme

**Comment by AlexFlipnote** [comment]
Not accepting Reddit bots

**Comment by perryprog** [comment]
This isn't a reddit bot you meme this is the same one on ls.terminal

**Pull request closed without merging**
